<?php

namespace HomeBundle\Repository;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends \Doctrine\ORM\EntityRepository
{

    public function eventFromThisCategory($category_id)
    {
        $qb = $this->createQueryBuilder('e')
                    ->andWhere('e.category = :cat')
                    ->setParameter('cat', $category_id)
                    ->orderBy('e.startDate', 'DESC')
                    ->getQuery();

                return $qb->execute();
    }


    public function countAllEventsForThisCategory($category_id)
    {
        return $this->createQueryBuilder('e')
                  ->select('COUNT(e.id)')
                  ->andWhere('e.category = :cat')
                  ->setParameter('cat', $category_id)
                  ->getQuery()
                  ->getSingleScalarResult();

    }

}
