admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Admin:dashboard }

parks_homepage:
    path:     /parks
    defaults: { _controller: AdminBundle:Category:parks }

restaurants_homepage:
    path:     /restaurants
    defaults: { _controller: AdminBundle:Category:restaurants }

monuments_homepage:
    path:     /monuments
    defaults: { _controller: AdminBundle:Category:monuments }

events_homepage:
    path:     /events
    defaults: { _controller: AdminBundle:Category:events }

category_add_new:
    path:     /category/newone
    defaults: { _controller: AdminBundle:Category:new }
    methods:    [GET]

category_add_new_action:
    path:     /category/newone
    defaults: { _controller: AdminBundle:Category:newform }
    methods:  [POST]

listing_homepage:
    path:     /listing
    defaults: { _controller: AdminBundle:Admin:listing }

settings_homepage:
    path:     /settings
    defaults: { _controller: AdminBundle:Admin:settings }

profile_homepage:
    path:     /profile
    defaults: { _controller: AdminBundle:Admin:profile }

support_homepage:
    path:     /support
    defaults: { _controller: AdminBundle:Admin:support }
