# Route d'accès
admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Admin:dashboard }
# Fin de la route d'accès




# Routes des pages consultables
parks_homepage:
    path:     /parks
    defaults: { _controller: AdminBundle:Category:parks }

sports_homepage:
    path:     /sports
    defaults: { _controller: AdminBundle:Category:sports }

monuments_homepage:
    path:     /monuments
    defaults: { _controller: AdminBundle:Category:monuments }

events_homepage:
    path:     /events
    defaults: { _controller: AdminBundle:Category:events }

listing_homepage:
    path:     /listing
    defaults: { _controller: AdminBundle:Admin:listing }

support_homepage:
    path:     /support
    defaults: { _controller: AdminBundle:Admin:support }

status_homepage:
    path:     /status
    defaults: { _controller: AdminBundle:Admin:status }
# Fin des routes consultable




# Routes des formulaires

# Category
category_add_new:
    path:     /category/new
    defaults: { _controller: AdminBundle:Category:new }
    methods:  [GET]

category_add_new_action:
    path:     /category/new
    defaults: { _controller: AdminBundle:Category:newform }
    methods:  [POST]

# Edition des elements (Sports, Events, Monuments, Parks)
edit_event_admin:
    path:     /events/edit/{id}
    defaults: { _controller: AdminBundle:Category:edit }
    methods:  [GET]

edit_event_admin_action:
    path:     /events/edit/{id}
    defaults: { _controller: AdminBundle:Category:editform }
    methods:  [POST]
# Fin des routes des formulaires



# Routes des pages d'erreurs
error_homepage:
    path:     /error
    defaults: { _controller: AdminBundle:Admin:error }
