# Route d'accès
admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Admin:dashboard }
# Fin de la route d'accès




# Routes des pages consultables
parks_homepage:
    path:     /parks
    defaults: { _controller: AdminBundle:Category:parks }

restaurants_homepage:
    path:     /restaurants
    defaults: { _controller: AdminBundle:Category:restaurants }

monuments_homepage:
    path:     /monuments
    defaults: { _controller: AdminBundle:Category:monuments }

events_homepage:
    path:     /events
    defaults: { _controller: AdminBundle:Category:events }

listing_homepage:
    path:     /listing
    defaults: { _controller: AdminBundle:Admin:listing }

support_homepage:
    path:     /support
    defaults: { _controller: AdminBundle:Admin:support }
# Fin des routes consultable




# Routes des formulaires

# Category
category_add_new:
    path:     /category/new
    defaults: { _controller: AdminBundle:Category:new }
    methods:  [GET]

category_add_new_action:
    path:     /category/new
    defaults: { _controller: AdminBundle:Category:newform }
    methods:  [POST]
# Fin des routes des formulaires



# Routes des paramètres
settings_homepage:
    path:     /settings
    defaults: { _controller: AdminBundle:Admin:settings }

update_homepage:
    path:     /settings/update
    defaults: { _controller: AdminBundle:Admin:update }
    methods:  [GET]


# Routes des pages d'erreurs
error_homepage:
    path:     /error
    defaults: { _controller: AdminBundle:Admin:error }
